import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import React from 'react'
import HomePage from "@/next_pages/Home";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Adedonha Stop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main > */}
        <HomePage />
      {/* </main> */}
    </>
  );
}
